networks:
  default:
    name: systemd
services:
  devcontainer:
    cap_add:
    - SYS_ADMIN
    environment:
      PATH: /usr/bin:/run/current-system/sw/bin/
      container: docker
    hostname: devcontainer
    image: ghcr.io/lucernae/devcontainer-nix:80izimy6356wnyaybna4c9hkvfh8p5pf
    privileged: true
    stop_signal: SIGRTMIN+3
    sysctls: {}
    tmpfs:
    - /run
    - /run/wrappers
    - /tmp:exec,mode=777
    tty: true
    volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - /workspaces/devcontainer-nix:/workspace:cached
    - /workspaces/devcontainer-nix/.devcontainer/systemd/nixos/configuration.nix:/etc/nixos/configuration.nix:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
version: '3.4'

