name: Matrix Setup
on:
  workflow_call:
    outputs:
      matrix:
        description: "The matrix configuration for builds"
        value: ${{ jobs.setup.outputs.matrix }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      
      - name: Set matrix
        id: set-matrix
        run: |
          UNSTABLE_CONFIG=$(jq -c '.nixos.unstable' .github/versions.json)
          STABLE_CONFIG=$(jq -c '.nixos.stable' .github/versions.json)
          echo "matrix=$(echo "{\"nix_channel\":[$UNSTABLE_CONFIG,$STABLE_CONFIG]}" | jq -c .)" >> $GITHUB_OUTPUT 