name: Matrix Setup Base
on:
  workflow_call:
    outputs:
      matrix:
        description: "The matrix configuration for base builds"
        value: ${{ jobs.setup.outputs.matrix }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      
      - name: Set matrix
        id: set-matrix
        run: |
          # Get the channels from versions.json
          UNSTABLE_CHANNEL=$(jq -r '.nixos.unstable.nixos_channel' .github/versions.json)
          STABLE_CHANNEL=$(jq -r '.nixos.stable.nixos_channel' .github/versions.json)
          
          # Create the matrix configuration
          echo "matrix=$(cat << EOF | jq -c .
          {
            "nix_system": ["x86_64-linux", "aarch64-linux"],
            "nix_channel": ["$UNSTABLE_CHANNEL", "$STABLE_CHANNEL"]
          }
          EOF
          )" >> $GITHUB_OUTPUT 